# Generated by Django 4.2.11 on 2024-03-28 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=20)),
                ('recby', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=300)),
                ('user', models.CharField(max_length=20)),
            ],
        ),
    ]
