# Generated by Django 4.2.11 on 2024-03-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='type',
            field=models.CharField(default='tv show', max_length=20),
        ),
    ]
