# Generated by Django 4.2.11 on 2024-03-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showlist', '0003_show_watched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='image',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='show',
            name='recby',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='show',
            name='user',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='show',
            name='watched',
            field=models.BooleanField(default=False),
        ),
    ]
