# Generated by Django 4.2.11 on 2024-03-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showlist', '0004_alter_show_image_alter_show_recby_alter_show_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
