# Generated by Django 4.2.11 on 2024-03-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showlist', '0005_alter_show_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
