# Generated by Django 4.2.11 on 2024-04-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showlist', '0006_alter_show_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='genre',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='show',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
