# Generated by Django 4.2.11 on 2024-04-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showlist', '0007_alter_show_genre_alter_show_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='type',
            field=models.CharField(blank=True, default='tv show', max_length=20),
        ),
    ]
