# Generated by Django 4.2.11 on 2024-05-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showlist', '0008_alter_show_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='user',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
